baseurl = "/"
title = "Timeless ephiphany"
theme = "hugo-nederburg-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "asyraf-id"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-70772819-1"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[params]
  # Unmark to use post folder for images. Default is static folder.
  #usepostimgfolder = true
  slogan = "Notes from a stranger"
  description = "Cultivated thought of my life" # meta description
  # You need to set author to have an author bio. If you have a writer in the markdown file it will override this.
  author = "Asyraf Duyshart"
  authorLink = "https://asyraf.id/"
  bio = [
    "I sold my soul to capitalism, mortgage my heart to humanism."
  ]
  copyright = [
    "&copy; 2018 Asyraf Duyshart",
    "Nederburg Hugo Theme by [Appernetic](https://appernetic.io).",
    "A port of Tracks by Compete Themes."
  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "me@asyraf.id"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

  [[menu.main]]
  name = "Get in touch"
  url = "contact/"
  weight = 3

# this will also be in author bio if there is no writer.
  [params.social]
  facebook      = "https://www.facebook.com/AsyrafDuyshart"
  # googleplus    = "full profile url in googleplus"
  email         = "me@asyraf.id"
  twitter       = "https://twitter.com/asyrafduyshart"
  linkedin      = "https://www.linkedin.com/in/asyrafduyshart/"
  # stackoverflow = "full profile url in stackoverflow"
  instagram     = "https://instagram.com/asyrafduyshart"
  github        = "https://github.com/asyrafduyshart"
  # pinterest     = "full profile url in pinterest"
  rss           = true

# Add a writer, then use it in the markdown front matter like this: writer = "Lukas Herman"
  [params.writers]
    [params.writers."Asyraf Duyshart"]
    link = "https://asyraf.id"
    email = "me@asyraf.id"
    bio = [
      "I sold my soul to capitalism, mortgage my heart to humanism."
    ]
    facebook      = "https://www.facebook.com/AsyrafDuyshart"
    # googleplus    = "full profile url in googleplus"
    twitter       = "https://twitter.com/asyrafduyshart"
    linkedin      = "https://www.linkedin.com/in/asyrafduyshart/"
    # stackoverflow = "full profile url in stackoverflow"
    instagram     = "https://instagram.com/asyrafduyshart"
    github        = "https://github.com/asyrafduyshart"
    # pinterest     = "full profile url in pinterest"