version: 2
jobs:
  build:
    docker:
      - image: jnyo/docker-hugo-firebase:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: hugo -t hugo-nederburg-theme
      - deploy:
          branch: master
          command: firebase deploy --token "$FIREBASE_TOKEN"