version: 2
jobs:
  build:
    docker:
      - image: nohitme/hugo-firebase:latest
    working_directory: ~/
    steps:
      - checkout
      - run:
          name: "Hugo Version"
          command: hugo version
      - run:
          name: "Remove Public"
          command: rm -rf public
      - run:
          name: "Run Hugo"
          command: ls && hugo
      - run:
          name: "Check Data"
          command: cd public && ls          
      - run:
          name: "Deploy"
          command: firebase deploy --token "$FIREBASE_TOKEN"