version: 2
jobs:
  build:
    docker:
      - image: nohitme/hugo-firebase:latest
    steps:
      - checkout
      - run:
          name: "Hugo Version"
          command: hugo version
      - run:
          name: "Pull Hugo Theme"
          command: git submodule init && git submodule update
      - run:
          name: "Run Hugo"
          command: hugo
      - run:
          name: "Check Data"
          command: cd public && ls          
      - run:
          name: "Deploy"
          command: firebase deploy --token "$FIREBASE_TOKEN"